POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "+917796274488"
}

###
POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "otp": 9087, 
    "hash": "8ba02bea05e4fe38f1cbb4a92e8e518752af531b8be9c86ac9803909c0e8e2d0.1683569619712",
    "phone": "+917796274488"
}

#everytime after sending otp req above, change otp and hash
